# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create!(email:"StankEye@yahoo.com",password:"test")
User.create!(email:"MonkeyBall@Nintendo.com",password:"test")
User.create!(email:"JonnySnow",password:"test")

Post.create!(user_id:1, post_title:"What is Lorem Ipsum?", post_body:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.")
Post.create!(user_id:1, post_title:"Why do we use it?", post_body:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters")
Post.create!(user_id:1, post_title:"Where does it come from?", post_body:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33")
  
Post.create!(user_id:2, post_title:"Where can I get some?", post_body:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable.")
Post.create!(user_id:2, post_title:"The standard Lorem Ipsum passage, used since the 1500s", post_body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Post.create!(user_id:2, post_title:"de Finibus Bonorum et Malorum", post_body:"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia")
  
Post.create!(user_id:3, post_title:"1914 translation by H. Rackham", post_body:"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.")
Post.create!(user_id:3, post_title:"Lorem Ipsum", post_body:"Donec cursus mi id pretium sollicitudin. Quisque dictum ullamcorper nunc ac tincidunt. Phasellus pulvinar ex vel turpis egestas, vel tristique quam tempus. Donec vitae eros odio. Vestibulum viverra ante id orci fermentum, sit amet consequat neque aliquet. Nulla ultrices dolor commodo tellus euismod, aliquam tempus dui vehicula. Nulla finibus nulla eget nisi tristique, at venenatis elit dignissim. Morbi vitae lectus nec mi varius lobortis. Cras egestas vel lacus ut lobortis. Donec congue accumsan euismod. Mauris consequat orci turpis, vitae varius nibh faucibus at")
Post.create!(user_id:3, post_title:"Lorem Ipsum Part 2", post_body:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In non dictum augue, vel convallis nunc. Pellentesque eleifend enim vitae sem rutrum, eget scelerisque felis condimentum. Donec vitae aliquam velit, et sollicitudin turpis. Phasellus leo libero, molestie a volutpat pretium, eleifend in urna. Curabitur ac sollicitudin lorem, id feugiat sapien. Fusce nec convallis diam. In ligula augue, gravida a magna ac, hendrerit ullamcorper est. Aliquam faucibus enim id mollis facilisis. Curabitur ac diam eget nulla auctor tincidunt. Aliquam dictum tincidunt neque, sed mattis arcu laoreet ac. Donec auctor aliquam sem, id tincidunt ipsum pretium sit amet. Sed consectetur, dolor eu consectetur egestas, mi lacus suscipit orci, quis fermentum justo velit at quam. Quisque sodales nisi leo. Donec pharetra dignissim nulla id facilisis.")



